/*
Base de datos destinada a una aplicacion de call center que registre domicilios, clientes, reclamos, usuarios, permisos, etc.
Se hace la relacion muchos a muchos sobre los Clientes y sus domicilios (y visceversa).
Tambien se cargan las provincias y localidades en distintas tablas.
*/

CREATE DATABASE CALL_CENTER
GO
USE CALL_CENTER
GO
CREATE TABLE PROVINCIAS(
    ID TINYINT PRIMARY KEY NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR(100) NOT NULL,
    ESTADO BIT DEFAULT 1 NOT NULL,
)
GO
CREATE TABLE LOCALIDADES(
    ID TINYINT PRIMARY KEY NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    ID_PROVINCIA TINYINT NOT NULL FOREIGN KEY REFERENCES PROVINCIAS(ID),
    ESTADO BIT DEFAULT 1 NOT NULL
)
GO
CREATE TABLE DOMICILIOS(
    ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    ID_PROVINCIA TINYINT NOT NULL FOREIGN KEY REFERENCES PROVINCIAS(ID),
    ID_LOCALIDAD TINYINT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(ID),
    NOMBRE_CALLE VARCHAR(60) NOT NULL,
    NUMERO TINYINT NULL,
    PISO TINYINT NULL,
    DEPARTAMENTO VARCHAR(5) NULL,
    ENTRECALLE_1 VARCHAR(60) NULL,
    ENTRECALLE_2 VARCHAR(60) NULL,
    OBSERVACION VARCHAR (100) NOT NULL
)
GO
CREATE TABLE ROLES(
    ID TINYINT PRIMARY KEY NOT NULL IDENTITY(1,1),
    DESCRIPCION_ROL VARCHAR(20) NOT NULL,
    ESTADO BIT DEFAULT 1 NOT NULL
)
GO
CREATE TABLE CLIENTES(
    ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    DNI VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(70) NOT NULL,
    TELEFONO_1 VARCHAR(20) NOT NULL,
    TELEFONO_2 VARCHAR(20) NULL,
    FECHA_NACIMIENTO DATE NOT NULL CHECK (FECHA_NACIMIENTO <= GETDATE()),
    FECHA_ALTA DATE DEFAULT GETDATE() NOT NULL,
    FECHA_BAJA DATE NULL CHECK (FECHA_BAJA <= GETDATE()),
    ESTADO BIT DEFAULT 1 NOT NULL 
)
GO
CREATE TABLE USUARIOS(
    ID INT PRIMARY KEY NOT NULL IDENTITY(1000,1),
    DNI VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(70) NOT NULL,
    PASSWORD VARCHAR (40) NOT NULL,
    TELEFONO_1 VARCHAR(20) NOT NULL,
    TELEFONO_2 VARCHAR(20) NULL,
    FECHA_INICIO DATE DEFAULT GETDATE() NOT NULL,
    ROL TINYINT NOT NULL FOREIGN KEY REFERENCES ROLES(ID),
    ESTADO BIT DEFAULT 1 NOT NULL
)
GO
CREATE TABLE TIPOS(
    ID TINYINT PRIMARY KEY NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR(30) NOT NULL,
    ESTADO BIT DEFAULT 1 NOT NULL,
)
GO
CREATE TABLE PRIORIDADES(
    ID TINYINT PRIMARY KEY NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR(30) NOT NULL,
    ESTADO BIT DEFAULT 1 NOT NULL
)
GO
CREATE TABLE ESTADOS_RECLAMO(
    ID TINYINT PRIMARY KEY NOT NULL IDENTITY(1,1),
    NOMBRE VARCHAR(30) NOT NULL,
    ESTADO BIT DEFAULT 1 NOT NULL
)
GO
CREATE TABLE RECLAMOS(
    ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    ID_TIPO TINYINT NOT NULL FOREIGN KEY REFERENCES TIPOS(ID),
    ID_PRIORIDAD TINYINT NOT NULL FOREIGN KEY REFERENCES PRIORIDADES(ID),
    DESCRIPCION_INICIAL VARCHAR(50) NOT NULL,
    DESCRIPCION_CIERRE VARCHAR(50) NULL,
    USUARIO_ASIGNADO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID),
    CLIENTE_AFECTADO INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(ID),
    FECHA_INICIO DATE DEFAULT GETDATE()  NOT NULL,
    FECHA_FIN DATE NULL CHECK (FECHA_FIN <= GETDATE()), 
    ID_ESTADO TINYINT FOREIGN KEY REFERENCES ESTADO_RECLAMO(ID)
)
GO
CREATE TABLE CLIENTES_X_DOMICILIOS (
    ID_CLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(ID),
    ID_DOMICILIO INT NOT NULL FOREIGN KEY REFERENCES DOMICILIOS(ID),
    PRIMARY KEY (ID_CLIENTE, ID_DOMICILIO),
    ESTADO BIT DEFAULT 1 NOT NULL
)
GO

